Release candidate v0.0.2
KCollins/conjugate-map pull request #3
Opened 2024-05-22 18:58 UTC by KCollins

Significant refactoring and feature additions. Now ready for initial release.

2024-05-22 20:16 UTC, aburrell requested changes
Found some changes!

2024-05-22 20:16 UTC, aburrell commented on CHANGELOG.md
> +[0.1.X] - 2024-XX-xx
```suggestion
[0.2.0] - 2024-05-23
```

2024-05-22 20:16 UTC, aburrell commented on CHANGELOG.md
> +
```suggestion
* Added community documentation
* Refactored code base to enable installation
* Created directory for notebooks

```

Check and make sure all changes are recored here.

2024-05-22 20:16 UTC, aburrell commented on CONTRIBUTING.md
> +3. Update the author list in ``zenodo.json``, if applicable
```suggestion
3. Update the author list in ``zenodo.json`` and ``CITATION.cff``, if applicable
```

2024-05-22 20:16 UTC, aburrell commented on CONTRIBUTING.md
> +In general, `conjugate=map` follows PEP8 and numpydoc guidelines.  Pylint
```suggestion
In general, `conjugate_map` follows PEP8.  Pylint
```

2024-05-22 20:16 UTC, aburrell commented on CONTRIBUTING.md
> +   see the discussion there for a full list of this shorthand notation.
```suggestion
   git commit -m "Brief description of your changes"
   ```
```

Removing this, since you don't use it in your commits.

2024-05-22 20:16 UTC, aburrell commented on README.md
>  Run in Binder here: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/KCollins/conjugate-map/HEAD?labpath=ConjugateMap.ipynb)
Check that this link still works.

2024-05-22 20:16 UTC, aburrell commented on README.md
>   - `calc_mlat_rings()` : function to calculate magnetic graticules for a given latitude and datetime.
These lines and the line above should be updated to be, e.g., `conjugate_map.calc_mlat_rings`

2024-05-22 20:16 UTC, aburrell commented on conjugate_map/conjCalcFunctions.py
> +def findconj(lat, lon, ut = dt.datetime.utcnow(), is_verbose = 0, method = 'aacgm', limit = 60):
`dt.datetime.utcnow` has been deprecated: https://discuss.python.org/t/deprecating-utcnow-and-utcfromtimestamp/26221.  Also, `is_verbose` should be a boolean (False/True).

2024-05-22 20:16 UTC, aburrell commented on pyproject.toml
> +version = "0.0.2"
```suggestion
version = "0.2.0"
```

Changing version based on versioning of initial release.

2024-05-23 14:13 UTC, KCollins commented on .github/pull_request_template.md
> +- [ ] Update zenodo.json file for new code contributors
```suggestion
- [ ] Update zenodo.json file and CITATION.cff file for new code contributors
```

2024-05-23 14:14 UTC, KCollins commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at agb073000@utdallas.edu. The project
```suggestion
reported by contacting the project team at kvcollins@spacescience.org. The project
```

2024-05-23 14:15 UTC, KCollins commented on CONTRIBUTING.md
> +  [GitHub](https://github.com//KCollins/conjugate-map/issues)
```suggestion
  [GitHub](https://github.com//KCollins/conjugate_map/issues)
```

2024-05-23 14:16 UTC, KCollins commented on CONTRIBUTING.md
> +When [reporting a bug](https://github.com//KCollins/conjugate-map/issues) please
```suggestion
When [reporting a bug](https://github.com//KCollins/conjugate_map/issues) please
```

2024-05-23 14:16 UTC, KCollins commented on CONTRIBUTING.md
> +[issue](https://github.com/KCollins/conjugate-map/issues).
```suggestion
[issue](https://github.com/KCollins/conjugate_map/issues).
```

2024-05-23 14:16 UTC, KCollins commented on CONTRIBUTING.md
> +To set up `conjugate-map` for local development:
```suggestion
To set up `conjugate_map` for local development:
```

2024-05-23 14:16 UTC, KCollins commented on CONTRIBUTING.md
> +1. [Fork pysat on GitHub](https://github.com/KCollins/conjugate-map/fork).
```suggestion
1. [Fork pysat on GitHub](https://github.com/KCollins/conjugate_map/fork).
```

2024-05-23 14:17 UTC, KCollins commented on CONTRIBUTING.md
> +1. [Fork pysat on GitHub](https://github.com/KCollins/conjugate-map/fork).
```suggestion
1. [Fork conjugate_map on GitHub](https://github.com/KCollins/conjugate-map/fork).
```

2024-05-23 14:17 UTC, KCollins commented on CONTRIBUTING.md
> +    git clone git@github.com:your_name_here/conjugate-map.git
```suggestion
    git clone git@github.com:your_name_here/conjugate_map.git
```

2024-05-23 14:19 UTC, KCollins commented on CONTRIBUTING.md
> +In general, `conjugate=map` follows PEP8 and numpydoc guidelines.  Pylint
```suggestion
In general, `conjugate_map` follows PEP8 and numpydoc guidelines.  Pylint
```

2024-05-23 14:29 UTC, KCollins commented on conjugate_map/conjCalcFunctions.py
> +def findconj(lat, lon, ut = dt.datetime.utcnow(), is_verbose = 0, method = 'aacgm', limit = 60):
```suggestion
def findconj(lat, lon, ut = dt.datetime.utcnow(), is_verbose = False, method = 'aacgm', limit = 60):
```

2024-05-23 14:36 UTC, aburrell commented on conjugate_map/conjCalcFunctions.py
>          is_verbose  : if set to True/1, prints debugging text
```suggestion
        is_verbose  : if set to True, prints debugging text
```

2024-05-23 14:51 UTC, aburrell commented on README.md
>  Run in Binder here: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/KCollins/conjugate-map/HEAD?labpath=ConjugateMap.ipynb)
Addressed in Issue #9

2024-05-23 14:52 UTC, aburrell commented on README.md
>   - `calc_mlat_rings()` : function to calculate magnetic graticules for a given latitude and datetime.
Created issue #11

2024-05-23 14:54 UTC, aburrell approved these changes
Found many things and fixed them, others are documented.

2024-05-23 14:55 UTC, merged